
def call(Map stageParams) {
 
// Code Generated by "Generate Pipeline Script" 
// checkout([
//      $class: 'GitSCM', 
//      branches: [[name: '*/master']], 
//      doGenerateSubmoduleConfigurations: false, extensions: [], 
//      submoduleCfg: [], 
//      userRemoteConfigs: [[url: 'https://github.com/shary786/jenkins-shared-library-structure.git']]
 
// ])
 
     checkout([
        $class: 'GitSCM',
        branches: [[name:  stageParams.branch ]],
        userRemoteConfigs: [[ credentialsId:stageParams.credentialsId, url: stageParams.url ]]
    ])
 
 }
